server:
  port: 8889
spring:  application:
    name: config-service
  cloud:    config:      server:        git:          uri: https://github.com/barry-zhang-g/vehicle_config.git          search-paths:            - location-service
            - car-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:7001/eureka
  instance:
    hostname: localhost